apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deployment
  template:
    metadata:
      labels:
        app: Deployment
    spec:
      containers:
        - name: node-app
          image: ausaf009/node-app:master-31b00cf7a617db3a21859ba2ada7df753c24f03a
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
