apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: node-app
          image: ausaf009/node-app:master-0a6e92146b3caf5fd0a40561d2665035da2299f6
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
