apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deployment
  template:
    metadata:
      labels:
        app: Deployment
    spec:
      containers:
        - name: node-app
          image: ausaf009/node-app:master-b51e53ca1940cd64fb5136c7c87172eb8b0838f0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
