apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deploymentnt
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: node-app
          image: ausaf009/node-app:master-babc634794731420517be536b9a4a9df8c209bdb
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
