apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
  namespace: Default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Deployment
  template:
    metadata:
      labels:
        app: Deployment
    spec:
      containers:
        - name: node-app
          image: ausaf009/node-app:master-0716bbd82d162c67da5028e91ca7ff23313a879c
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
